---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data
```{r, echo=TRUE}
activity <- read.csv('activity.csv')
```


## What is mean total number of steps taken per day?
```{r,echo=TRUE}
totaldailysteps<-tapply(activity$steps,activity$date,sum)
hist(totaldailysteps)
```

```{r,echo=TRUE}
mean(totaldailysteps,na.rm=TRUE)
median(totaldailysteps,na.rm = TRUE)
```

## What is the average daily activity pattern?
```{r,echo=TRUE}
activityNoNa <- subset(activity, !is.na(steps))
intervals <- unique(activityNoNa$interval)
meanstepsperinterval<-tapply(activityNoNa$steps,activityNoNa$interval,mean)
plot(intervals,meanstepsperinterval,type="l")
```


```{r,echo=TRUE}
indexmaximum <- which(meanstepsperinterval==max(meanstepsperinterval),arr.ind = TRUE)[1]
intervalmax <- intervals[indexmaximum]
intervalmax
```

## Imputing missing values
```{r,echo=TRUE}
TotalNas <- (dim(activity)[1]-dim(activityNoNa)[1])
sum(is.na(activity$steps))
```

```{r,echo=TRUE}
#impute missing values with average of interval
#create new data frame with imputed missing values
activity$meanStepsperInterval<-rep(round(meanstepsperinterval),61)
activity$steps[is.na(activity$steps)] <- 
    activity$meanStepsperInterval[is.na(activity$steps)]
newdata <- subset(activity, select = steps:interval)
```

```{r,echo=TRUE}
newtotaldailysteps<-tapply(newdata$steps,newdata$date,sum)
hist(newtotaldailysteps)
```

```{r,echo=TRUE}
mean(newtotaldailysteps,na.rm=TRUE)
median(newtotaldailysteps,na.rm = TRUE)
```

## Are there differences in activity patterns between weekdays and weekends?
```{r,echo=TRUE}
#create categorical variable
newdata$wday<-weekdays(as.Date(newdata$date))
newdata$wday[newdata$wday=="Sunday" | newdata$wday=="Saturday"]<-"weekend"
newdata$wday[newdata$wday!="weekend"]<-"weekday"
newdata$wday<-as.factor(newdata$wday)
```

```{r,echo=TRUE}
require(lattice)
xyplot(steps ~ interval | wday, data = newdata,       
       layout = c(1,2), type = "l", col="blue",
       xlab="Interval", ylab="Number of steps",
       ylim=c(-15,240), 
       panel = function(x, y, ...) {
           panel.average(x, y, ...,horizontal=FALSE)
           })
```
